import HeaderModule from '@/modules/Header'
import InfographicsModule from '@/modules/Infographics'
import ServiceCardsModule from '@/modules/ServiceCards'
import StartBannerModule from '@/modules/StartBanner'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <HeaderModule/>
        <StartBannerModule/>
        <InfographicsModule/>
        <ServiceCardsModule/>
      </main>
    </>
  )
}
